version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: command_service_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  
  mongodb:
    image: mongo:latest
    container_name: query_service_mongodb_db
    environment:
      MONGO_INITDB_DATABASE: query_service_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
