spring:
  application:
    name: Query Service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: orders-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8081
