spring:
  application:
    name: Query Service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: query_service_db

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: query-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.json.type.mapping]": "product.created:order.system.cqrs.queryservice.events.ProductCreatedEvent,order.created:order.system.cqrs.queryservice.events.OrderCreatedEvent,product.price.changed:order.system.cqrs.queryservice.events.ProductPriceChangedEvent,product.deactivated:order.system.cqrs.queryservice.events.ProductDeactivatedEvent"
server:
  port: 8081
