spring:
  application:
    name: Command Service

  datasource:
    url: jdbc:postgresql://localhost:5432/command_service_db
    username: margus
    password: margus123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create # para que JPA cree/actualice tablas automáticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  jpa.show-sql: false

  kafka:
    bootstrap-servers: localhost:9094 # Dirección del broker Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": "product.created:order.system.cqrs.commandservice.events.ProductCreatedEvent, order.created:order.system.cqrs.commandservice.events.OrderCreatedEvent"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: orders-group

server:
  port: 8080
