spring:
  application:
    name: Command Service

  datasource:
    url: jdbc:postgresql://localhost:5432/command_service_db
    username: margus
    password: margus123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # para que JPA cree/actualice tablas automáticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  # Opcional: mostrar las consultas SQL en consola (útil para debugging)
  jpa.show-sql: false
  jpa.properties.hibernate.format_sql: false

  kafka:
    bootstrap-servers: localhost:9094 # Dirección del broker Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: orders-group
server:
  port: 8080
